version: '3.8'

services:

  weather_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_analytics_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - WEATHERAPI_API_KEY=${WEATHERAPI_API_KEY}
      - WEATHERBIT_API_KEY=${WEATHERBIT_API_KEY}
      - WEATHERSTACK_API_KEY=${WEATHERSTACK_API_KEY}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT:-5}
    depends_on:
      - mongodb
    networks:
      - weather_network

  mongodb:
    image: mongo:latest
    container_name: weather_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - weather_network

volumes:
  mongo_data:

networks:
  weather_network:
    driver: bridge

