version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: weather_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weather_dwh_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbt:
    build:
      context: ../dbt
      dockerfile: Dockerfile
    container_name: weather_dbt
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DBT_PROFILES_DIR: /dbt
      DBT_PROJECT_DIR: /dbt
    volumes:
      - ../dbt:/dbt
    networks:
      - weather_dwh_network
    depends_on:
      postgres:
        condition: service_healthy
    # Интерактивный режим - оставляем контейнер запущенным
    stdin_open: true
    tty: true
    command: tail -f /dev/null

volumes:
  postgres_data:
  dbt_packages:
  dbt_target:

networks:
  weather_dwh_network:
    driver: bridge
